[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION  = "20"
  NPM_VERSION   = "10"
  NITRO_PRESET  = "netlify"

[functions]
  directory    = ".output/server"
  node_bundler = "esbuild"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
